### ISSUE TITLE
Need script to pull the final model together from the final checkpoint.

### ISSUE THREAD

**Issue by Nottlespike** [PrimeIntellect-ai/prime-diloco#121]
It may be in one of the many branches but I can't find a script to take the final checkpoint and construct, validate, and output a final modelfile. I attempted to make my own but failed for hard to understand reasons relating to:
```
(prime) (base) kearm@KDT:~/prime$ python src/zeroband/load-final-model.py
Traceback (most recent call last):
  File "/home/kearm/prime/src/zeroband/load-final-model.py", line 99, in <module>
    main()
  File "/home/kearm/prime/src/zeroband/load-final-model.py", line 81, in main
    model, tokenizer = load_final_model()
                       ^^^^^^^^^^^^^^^^^^
  File "/home/kearm/prime/src/zeroband/load-final-model.py", line 46, in load_final_model
    ckpt_manager = CkptManager(
                   ^^^^^^^^^^^^
  File "/home/kearm/prime/src/zeroband/checkpoint.py", line 252, in __init__
    self.world_info = get_world_info()
                      ^^^^^^^^^^^^^^^^
  File "/home/kearm/prime/src/zeroband/utils/world_info.py", line 55, in get_world_info
    world_info = WorldInfo()
                 ^^^^^^^^^^^
  File "/home/kearm/prime/src/zeroband/utils/world_info.py", line 15, in __init__
    self.world_size = int(os.environ["WORLD_SIZE"])
                          ~~~~~~~~~~^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'WORLD_SIZE'
```

**Comment by Jackmin801** [comment]
Its a bit messy rn. But you can use the script from here: https://github.com/PrimeIntellect-ai/prime/pull/123
Seems to work for our model that is currently training.
You should then be able to load the model using huggingface `AutoModelForCausalLM`

Example usage:
```bash
python scripts/export_dcp.py @configs/10B/H100.toml --ckpt.path /data/intellect-1-step17000 --ckpt.resume /data/10b/step_17000/diloco_0
```
