### ISSUE TITLE
Terminate called after throwing an instance of 'gloo::EnforceNotMet'

### ISSUE THREAD

**Issue by Jackmin801** [PrimeIntellect-ai/prime-diloco#68]
```python
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at ../third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 1046204 vs 1040256
```

```
3:22:58 [INFO] [Rank 0] step: 1243, loss: 6.9328, tokens_per_second: 89291.13, mfu: 18.21, diloco_peers: 3
03:22:58 [INFO] [Rank 1] step: 1244, loss: 6.9331, tokens_per_second: 89174.58, mfu: 18.19, diloco_peers: 3
03:22:58 [INFO] [Rank 0] step: 1244, loss: 6.9331, tokens_per_second: 89167.91, mfu: 18.19, diloco_peers: 3
03:22:59 [INFO] [Rank 1] step: 1245, loss: 6.9320, tokens_per_second: 88825.29, mfu: 18.12, diloco_peers: 3
03:22:59 [INFO] [Rank 0] step: 1245, loss: 6.9320, tokens_per_second: 88890.52, mfu: 18.13, diloco_peers: 3
03:23:00 [INFO] [Rank 1] step: 1246, loss: 6.9330, tokens_per_second: 89463.72, mfu: 18.25, diloco_peers: 3
03:23:00 [INFO] [Rank 0] step: 1246, loss: 6.9330, tokens_per_second: 89447.74, mfu: 18.24, diloco_peers: 3
03:23:01 [INFO] [Rank 1] step: 1247, loss: 6.9332, tokens_per_second: 89498.89, mfu: 18.25, diloco_peers: 3
03:23:01 [INFO] [Rank 0] step: 1247, loss: 6.9332, tokens_per_second: 89560.09, mfu: 18.27, diloco_peers: 3
03:23:01 [INFO] [Rank 1] step: 1248, loss: 6.9327, tokens_per_second: 89171.89, mfu: 18.19, diloco_peers: 3
03:23:01 [INFO] [Rank 0] step: 1248, loss: 6.9327, tokens_per_second: 89152.21, mfu: 18.18, diloco_peers: 3
03:23:02 [INFO] [Rank 1] step: 1249, loss: 6.9329, tokens_per_second: 88780.76, mfu: 18.11, diloco_peers: 3
03:23:02 [INFO] [Rank 0] step: 1249, loss: 6.9329, tokens_per_second: 88753.56, mfu: 18.10, diloco_peers: 3
03:23:03 [INFO] [Rank 1] step: 1250, loss: 6.9332, tokens_per_second: 88971.50, mfu: 18.15, diloco_peers: 3
03:23:03 [INFO] [Rank 0] step: 1250, loss: 6.9332, tokens_per_second: 88967.54, mfu: 18.14, diloco_peers: 3
03:23:03 [DEBUG] [Rank 1] Pre diloco model: a88383daf2eb872e47032b7153142951
03:23:03 [DEBUG] [Rank 0] Pre diloco model: a88383daf2eb872e47032b7153142951
03:23:03 [DEBUG] [Rank 1] 
03:23:03 [DEBUG] [Rank 1] [B] Resolving world
03:23:03 [DEBUG] [Rank 0] 
03:23:03 [DEBUG] [Rank 0] [B] Resolving world
03:23:03 [DEBUG] [Rank 1] World resolved in 0.0005263998173177242 seconds
03:23:03 [DEBUG] [Rank 0] World resolved in 0.0006461699958890676 seconds
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at ../third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 1046204 vs 1040256
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at ../third_party/gloo/gloo/transport/tcp/pair.cc:446] op.preamble.length <= op.nbytes. 1046204 vs 1040256
E1009 03:23:04.083000 124214882889728 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 0 (pid: 28549) of binary: /root/ZeroBand/.venv/bin/python3
Traceback (most recent call last):
  File "/root/ZeroBand/.venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/root/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/root/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/ZeroBand/.venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
src/zeroband/train.py FAILED
------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-09_03:23:04
  host      : b5e2f0d922ef
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 28550)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 28550
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-09_03:23:04
  host      : b5e2f0d922ef
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 28549)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 28549
======================================================
```

It seems that this will fail the PG destruction?

**Comment by Jackmin801** [comment]
Unable to reproduce, closing for now
